project:
  type: website
  output-dir: docs

#profile:
#  default: japanese
#  group: [japanese, english]

website:
  title: "Kimiho OMAE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publication.qmd
        text: Publication

format:
  html:
    theme:
      light: litera.scss
      dark: superhero
    css: styles.css
    toc: true

