project:
  type: website
  output-dir: docs

website:
  title: "Kimiho OMAE, Ph.D."
  navbar:
    left:
      - text: Home
        menu:
        - href: index.qmd
          text: English
        - href: home_ja.qmd
          text: Japanese
      - href: publication.qmd
        text: Publications
      - href: tools.qmd
        text: Tools
#    right: 
#      - href: index.qmd
#        text: English
#      - href: home_ja.qmd
#        text: Japanese

format:
  html:
    theme:
      light: litera.scss
      dark: superhero
    css: styles.css
    toc: true
