project:
  type: website
  output-dir: docs

website:
  title: "Kimiho OMAE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publication.qmd
        text: Publication
      - href: tools.qmd
        text: Tools
    right: 
      - href: index.qmd
        text: English
      - href: home_ja.qmd
        text: Japanese

format:
  html:
    theme:
      light: litera.scss
      dark: superhero
    css: styles.css
    toc: true
