project:
  type: website
  output-dir: docs

website:
  title: "Kimiho OMAE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About
        menu:
        - href: about_en.qmd
          text: English
        - href: about_ja.qmd
          text: Japanese
      - href: publication.qmd
        text: Publications
      - href: tools.qmd
        text: Tools
#    right: 
#      - href: index.qmd
#        text: English
#      - href: home_ja.qmd
#        text: Japanese

format:
  html:
    theme:
      light: litera.scss
      dark: superhero
    css: styles.css
    toc: true
