---
execute:
  echo: false
  message: false
  warning: false
---

# News {{< fa newspaper >}}

---

::: {.scroll-box}

**2025/03/26-28. Gave an oral presentation**<br>
<div style="margin-left: 1em;">
Society for the Study of the Origin and Evolution of Life Japan (SSOEL), The 49th Annual Meeting at Yokohama.
</div>

**2025/02/24. A preprint I co-authored is now available!**<br>
<div style="margin-left: 1em;">
Konno *et al*. "Repeatability of protein structural evolution following convergent gene fusions". [*bioRxiv* (2025)](https://doi.org/10.1101/2025.02.23.639786) / [X post (@utnk1)](https://x.com/utnk1/status/1894018943267795408)
</div>

**2024/04/30. A paper I co-authored has been published in the PNAS Journal!**<br>
<div style="margin-left: 1em;">
Tominaga *et al*. "Frequent Nonhomologous Replacement of Replicative Helicase Loaders by Viruses in *Vibrionaceae*". [*Proc Natl Acad Sci USA* (2024)](https://doi.org/10.1073/pnas.2317954121)
</div>

**2023/11/28-29. Gave an poster presentation**<br>
<div style="margin-left: 1em;">
Society for Japanese Society of Microbial Ecology (JSME), The 36th Annual Meeting at Hamamatsu.
</div>

**2023/07/20. A paper I co-authored has been published in the Archives of Microbiology Journal!**<br>
<div style="margin-left: 1em;">
Nishida *et al*. "Construction of multiple metagenome assembled genomes containing carbon monoxide dehydrogenases from anaerobic carbon monoxide enrichment cultures". [*Arch Microbiol* (2023)](https://doi.org/10.1007/s00203-023-03635-4)
</div>

**2023/03/02. Gave an oral presentation**<br>
<div style="margin-left: 1em;">
Society of Genome Microbiology, Japan (SGMJ), The 17th Annual Meeting at Kisarazu.
</div>

**2022/11/01-02. Gave an poster presentation**<br>
<div style="margin-left: 1em;">
Society for Japanese Society of Microbial Ecology (JSME), The 35th Annual Meeting at Sapporo. <span style="color:red">Received the Excellence Award (second place of 30) in postdoc poster presentation section!</span><br>
</div>

**2022/08/06. Gave an oral presentation**<br>
<div style="margin-left: 1em;">
Society for Evolutionary Studies, Japan (SESJ), The 24th Annual Meeting at Numazu. <span style="color:red">Won the best postdoc oral presentation award!</span><br>
</div>

**2022/03/02. Gave an oral presentation**<br>
<div style="margin-left: 1em;">
Society of Genome Microbiology, Japan (SGMJ), The 16th Annual Meeting (Online).
</div>

:::

# About  {{< fa circle-info >}}

---

### Education

<div style="margin-left: 1em;">

**2020Mar.** Ph.D., Division of Applied Biosciences, Kyoto University<br>
**2016Mar.** Master of Agriculture, Division of Applied Biosciences, Kyoto University<br>
**2014Mar.** Bachelor of Agriculture, Department of Bioresource Science, Kyoto University<br>

</div>

### Work experience

<div style="margin-left: 1em;">

**2024Apr-Now.**<br>
Researcher at [Geobiology and Astrobiology Laboratory](https://www.riken.jp/en/research/labs/chief/geobiol_astrobiol/index.html) (RIKEN Cluster for Pioneering Research (CPR), RIKEN)

**2020Apr-2024Mar.**<br>
Postdoc (Department of Integrated Biosciences, Graduate School of Frontier Sciences, the University of Tokyo)

**2016Apr-2019Mar.**<br>
Research Fellow, Japan Society for the Promotion of Science (DC1) at [Laboratory of Marine Microbiology](http://www.google.com/url?q=http%3A%2F%2Fwww.microbiology.marine.kais.kyoto-u.ac.jp%2F&sa=D&sntz=1&usg=AOvVaw1hlrXyxdodQNS_s643cNXA) (Division of Applied Biosciences, Graduate School of Agriculture, Kyoto University)

</div>

# Research topics {{< fa microscope >}}

---

### Keywords

<div style="margin-left: 1em;">

Microbiology {{< fa bacterium >}}, Extremophiles {{< fa volcano >}}, Bioinformatics {{< fa computer >}}, Comparative genomics {{< fa dna >}}

</div>

### Projects

<div style="margin-left: 1em;">

**2024Apr-Now.**<br>
[Geochemistry of CO worlds](https://en.co-world.jp/) (Transformative Research Areas (A): A03 Biology Group)

**2020Apr-2024Mar.**<br>
Bioinformatics for predicting new functions in DNA sequence space (CREST project)

**2014Apr-2020Mar.**<br>
Genomic and molecular ecological studies on thermophilic hydrogenogenic carboxydotrophs

</div>

# Awards {{< fa award >}}

---

- **2022/11/01-02.** Society for Japanese Society of Microbial Ecology (JSME), The 35th Annual Meeting at Sapporo.<br>
<span style="color:red">Received the Excellence Award (second place of 30) in postdoc poster presentation section.</span><br>

- **2022/08/06.** Society for Evolutionary Studies, Japan (SESJ), The 24th Annual Meeting at Numazu.<br>
<span style="color:red">Won the best postdoc oral presentation award.</span><br>
