---
execute:
  echo: false
  message: false
  warning: false
---

# News {{< fa newspaper >}}

---

::: {.scroll-box}

**2025/05/10. 共著に加わった論文のプレプリントが公開されました！**<br>
<div style="margin-left: 1em;">
Nishimura *et al*. "CORGIAS: identifying correlated gene pairs by considering evolutionary history in a large-scale prokaryotic genome dataset". [*bioRxiv* (2025)](https://doi.org/10.1101/2025.05.07.652372) / [X post (@ynishimuraLv)](https://x.com/ynishimuraLv/status/1921396105838797230)
</div>

**2025/03/26-28. 口頭発表を行いました。**<br>
<div style="margin-left: 1em;">
第49回生命の起原および進化学会学術講演会（横浜）
</div>

**2025/02/24. 共著に加わった論文のプレプリントが公開されました！**<br>
<div style="margin-left: 1em;">
Konno *et al*. "Repeatability of protein structural evolution following convergent gene fusions". [*bioRxiv* (2025)](https://doi.org/10.1101/2025.02.23.639786) / [X post (@utnk1)](https://x.com/utnk1/status/1894018943267795408)
</div>

**2024/04/30. 共著に加わった論文が PNAS 誌から公開されました！**<br>
<div style="margin-left: 1em;">
Tominaga *et al*. "Frequent Nonhomologous Replacement of Replicative Helicase Loaders by Viruses in *Vibrionaceae*". [*Proc Natl Acad Sci USA* (2024)](https://doi.org/10.1073/pnas.2317954121)
</div>

**2023/11/28-29. ポスター発表を行いました。**<br>
<div style="margin-left: 1em;">
日本微生物生態学会第36回大会（浜松）
</div>

**2023/07/20. 共著に加わった論文が Archives of Microbiology 誌から公開されました！**<br>
<div style="margin-left: 1em;">
Nishida *et al*. "Construction of multiple metagenome assembled genomes containing carbon monoxide dehydrogenases from anaerobic carbon monoxide enrichment cultures". [*Arch Microbiol* (2023)](https://doi.org/10.1007/s00203-023-03635-4)
</div>

**2023/03/02. 口頭発表を行いました。**<br>
<div style="margin-left: 1em;">
第 17 回日本ゲノム微生物学会年会（木更津）
</div>

**2022/11/01-02. ポスター発表を行いました。**<br>
<div style="margin-left: 1em;">
日本微生物生態学会第35回大会（札幌）<span style="color:red">→ 優秀ポスター賞 博士号取得者の部 優秀賞（30演題中2位）を受賞しました！</span><br>
</div>

**2022/08/06. 口頭発表を行いました。**<br>
<div style="margin-left: 1em;">
日本進化学会年大会第24回沼津大会 <span style="color:red">→ ポスドク口頭発表賞 最優秀賞を受賞しました！</span><br>
</div>

**2022/03/02. 口頭発表を行いました。**<br>
<div style="margin-left: 1em;">
第 16 回日本ゲノム微生物学会年会
</div>

:::

# Career {{< fa circle-user >}}

---

### Education

<div style="margin-left: 1em;">

**2020Mar.** 京都大学大学院 農学研究科 応用生物科学専攻 博士後期 修了<br>
**2016Mar.** 京都大学大学院 農学研究科 応用生物科学専攻 修士課程 修了<br>
**2014Mar.** 京都大学 農学部 資源生物科学科 卒業<br>

</div>

### Work experience

<div style="margin-left: 1em;">

**2025Apr-Now. 研究員**<br>
理化学研究所 開拓研究所 [鈴木地球・惑星生命科学研究室](https://suzukimicrobe.riken.jp/)

**2024Apr-2025Mar. 研究員**<br>
理化学研究所 開拓研究本部 [鈴木地球・惑星生命科学研究室](https://suzukimicrobe.riken.jp/)

**2020Apr-2024Mar. 特任研究員**<br>
東京大学大学院 新領域創成科学研究科 先端生命科学専攻

**2016Apr-2019Mar. 日本学術振興会 特別研究員 (DC1)**<br>
京都大学大学院 農学研究科 応用生物科学専攻（[海洋分子微生物学分野](http://www.google.com/url?q=http%3A%2F%2Fwww.microbiology.marine.kais.kyoto-u.ac.jp%2F&sa=D&sntz=1&usg=AOvVaw1hlrXyxdodQNS_s643cNXA)）

</div>

# Research topics {{< fa microscope >}}

---

### Keywords

<div style="margin-left: 1em;">

微生物学 {{< fa bacterium >}} 極限微生物 {{< fa volcano >}} バイオインフォマティクス {{< fa computer >}} 比較ゲノム {{< fa dna >}}

</div>

### Projects

<div style="margin-left: 1em;">

**2024Apr-Now.**<br>
[CO 環境の生命惑星化学：CO world](https://co-world.jp/)（学術変革領域研究(A)：A03 生物班）

**2020Apr-2024Mar.**<br>
DNA 配列空間に新規機能を予測する情報技術（CREST プロジェクト）

**2014Apr-2020Mar.**<br>
好熱性水素生成型一酸化炭素資化菌のゲノム解析・分子生態

</div>

# Awards {{< fa award >}}

---

**2022/11/01-02. 日本微生物生態学会第35回大会（札幌）**<br>
<div style="margin-left: 1em;">
<span style="color:red">優秀ポスター賞 博士号取得者の部 優秀賞（30演題中2位）</span><br>
</div>

**2022/08/06. 日本進化学会年大会第24回沼津大会**<br>
<div style="margin-left: 1em;">
<span style="color:red">ポスドク口頭発表賞 最優秀賞</span><br>
</div>
